
# Setup
title:               Harendra Singh
email:               mail@harendrasingh.tech
tagline:             Personal Website of Harendra
url:                 "http://harendrasingh.tech/devProfile" # insert your site's URL
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              Xiaoying Riley
  url:               https://twitter.com/3rdwave_themes
  email:

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:UA-115060004-1
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: harendrasingh22
twitter_username: /
instagram_username: /
facebook: reviewrulezz.tk
linkedin_username: harendrasingh98
dribbble_username: /

# Custom vars
version:             1.0.1
github:
  repo:              https://github.com/kevit/devaid-jekyll-theme

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty

widgets:
  - title: About
    url: about
    archor: true
  - title: Features
    url: features
    archor: true
  - title: Docs
    url: docs
    archor: true
  - title: License
    url: license
    archor: true
  - title: Contact
    url: contact
    archor: true
  - title: Blog
    url: blog
  - title: Page
    url: page
